name: Build and Push Docker Image

on:
  push:
    branches:
      - github

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'  # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run Flake8
      run: flake8 .
  
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      #- name: Get current date
      #  id: date
      #  run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
      - name: Set current date as env variable
        id: tagname
        run: echo "::set-output name=timestamp::$(date +'%s')"
        
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/beffaco/test_kubernetes:${{ steps.tagname.outputs.timestamp }} . #${{ steps.date.outputs.date }} .

      - name: Push the Docker image
        run: |
          docker push ghcr.io/beffaco/test_kubernetes:${{ steps.tagname.outputs.timestamp }} #${{ steps.date.outputs.date }}
